### ISSUE TITLE
Undefined value in the demo file at gml_Script_sh_tags_define

### ISSUE THREAD

**Issue by VeroSquirrel** [zbanack/shampoo#2]
On a completely fresh project. I haven't added the framework to any already existing projects yet, I simply unpackaged it, and changed the current working directory to enable live editing in the shampoo object, and as soon as I try to run the demo, I get the following error. (Version 0_9_21)

___________________________________________
############################################################################################
ERROR in
action number 1
of Create Event
for object obj_shampoo:

DoSub :2: undefined value
 at gml_Script_sh_tags_define (line 633) -        for(var i = array_length(accepts)-1; i>=0; i--) {
############################################################################################
gml_Script_sh_tags_define (line 633)
gml_Script_sh_tags_init (line 531) -        sh_tags_define(ShTag.ITALIC,       ["i", "italic"],                            undefined, false, false,
gml_Script_anon_Shampoo_gml_GlobalScript_ShampooMain_5144_Shampoo_gml_GlobalScript_ShampooMain (line 193) -               sh_tags_init();
gml_Script_Shampoo (line 502) -        initialize();
gml_Script_shampoo_init (line 69)
gml_Object_obj_shampoo_Create_0 (line 8) -        false,

**Comment by zbanack** [comment]
Thanks for the report. GMS v2.3.2.556 changed how `undefined` works when passed into an array -- now throwing an error.

I'll get an official patch out in a few days, but for the time being please refer to this quick one-liner fix [https://itch.io/post/2993022](https://itch.io/post/2993022).

Thanks

**Comment by zbanack** [comment]
Resolved in minor release v0.9.3: https://zackbanack.itch.io/shampoo/devlog/245097/v093-minor-release 👍

**Comment by zbanack** [comment]
Resolved in minor release v0.9.3: https://zackbanack.itch.io/shampoo/devlog/245097/v093-minor-release 👍
