### ISSUE TITLE
commas in {$var} replacement not correctly handled

### ISSUE THREAD

**Issue by meseta** [zbanack/shampoo#4]
Having a comma in the value returned by `shampoo_var_replacement` gets replaced with the escape token.

The below should just say "Login timeout, please try again"
![image](https://user-images.githubusercontent.com/930832/138578113-ce31a57b-6fac-45e1-a2d5-e8d5b06a0402.png)

I looked into the cause of it. It seems to be because there is a period in `SH_ESC`, which, in `shampoo_sanitize` gets later replaced with another escape sequence. It looks like either SH_ESC should not contain a period, or the order of operations of shampoo_sanitize should replace the period first

```
	input = string_replace_all(input, SH_TKN_TAG_ESCAPE,	SH_INPUT_ESCAPE_ESCAPED);
	input = string_replace_all(input, SH_TKN_TAG_OPEN,		SH_INPUT_OPEN_ESCAPED);
	input = string_replace_all(input, SH_TKN_TAG_CLOSE,		SH_INPUT_CLOSE_ESCAPED);
	input = string_replace_all(input, SH_TKN_DOUBLE_QUOTE,	SH_INPUT_DOUBLE_QUOTE_ESCAPED);
	input = string_replace_all(input, SH_TKN_TAG_COMMA,		SH_INPUT_COMMA_ESCAPED);
	input = string_replace_all(input, SH_TKN_TAG_EQUALS,	SH_INPUT_EQUALS_ESCAPED);
	input = string_replace_all(input, SH_TKN_TAG_COLON,		SH_INPUT_COLON_ESCAPED);
	input = string_replace_all(input, SH_TKN_TAG_PERIOD,	SH_INPUT_PERIOD_ESCAPED);
```

**Comment by zbanack** [comment]
I believe I got this fixed in 0.9.4. 👍
